"""
Django settings for mi_proyecto project.  # Comentario: Indica que este archivo contiene la configuración del proyecto Django

Generated by 'django-admin startproject' using Django 3.2.2.  # Comentario: Indica cómo fue generado el archivo

For more information on this file, see  # Comentario: Referencia a la documentación de Django
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see  # Comentario: Referencia a la documentación completa de settings
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path  # Importa Path para manejar rutas de archivos de forma más sencilla

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Define la ruta base del proyecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ojd8!zuy5a$pnc)yi6aqy-so)_pe)uz)5t4z=rtr^ef9jm&^sb'  # Clave secreta para la seguridad del proyecto

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Activa el modo debug (no usar en producción)

ALLOWED_HOSTS = []  # Lista de hosts permitidos para acceder a la aplicación


# Application definition

INSTALLED_APPS = [  # Lista de aplicaciones instaladas en el proyecto
    'django.contrib.admin',  # Admin de Django
    'django.contrib.auth',  # Sistema de autenticación
    'django.contrib.contenttypes',  # Tipos de contenido
    'django.contrib.sessions',  # Manejo de sesiones
    'django.contrib.messages',  # Sistema de mensajes
    'django.contrib.staticfiles',  # Archivos estáticos
    'rest_framework',  # Django REST Framework para APIs
    'corsheaders',  # Manejo de CORS
    'clasificaciones',  # Aplicación personalizada para clasificaciones
    'inventario',  # Aplicación personalizada para inventario
    'pedidos',  # Aplicación personalizada para pedidos
    'talleres',  # Aplicación personalizada para talleres
    'usuarios',  # Aplicación personalizada para usuarios
]

MIDDLEWARE = [  # Lista de middlewares que procesan las peticiones/respuestas
    'corsheaders.middleware.CorsMiddleware',  # Middleware para CORS
    'django.middleware.security.SecurityMiddleware',  # Seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manejo de sesiones
    'django.middleware.common.CommonMiddleware',  # Funcionalidades comunes
    'django.middleware.csrf.CsrfViewMiddleware',  # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección contra clickjacking
]

ROOT_URLCONF = 'mi_proyecto.urls'  # Archivo principal de rutas del proyecto

TEMPLATES = [  # Configuración de los templates (plantillas HTML)
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Motor de plantillas de Django
        'DIRS': [],  # Directorios adicionales de plantillas
        'APP_DIRS': True,  # Busca plantillas en las apps instaladas
        'OPTIONS': {
            'context_processors': [  # Procesadores de contexto para las plantillas
                'django.template.context_processors.debug',  # Añade información de depuración
                'django.template.context_processors.request',  # Añade el objeto request
                'django.contrib.auth.context_processors.auth',  # Añade el usuario autenticado
                'django.contrib.messages.context_processors.messages',  # Añade mensajes
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_proyecto.wsgi.application'  # Configuración para WSGI (servidor web)


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {  # Configuración de la base de datos
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Motor de base de datos (MySQL)
        'NAME': 'king_importados',      # Nombre de la base de datos
        'USER': 'root',       # Usuario de la base de datos
        'PASSWORD': '1234',  # Contraseña de la base de datos
        'HOST': 'localhost',              # Host de la base de datos
        'PORT': '3306',                   # Puerto de la base de datos
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  # Configuración adicional de MySQL
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [  # Validadores de contraseñas para usuarios
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Valida similitud con atributos del usuario
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Valida longitud mínima
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Valida que no sea una contraseña común
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Valida que no sea solo numérica
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-AR'  # Código de idioma por defecto

TIME_ZONE = 'UTC'  # Zona horaria por defecto

USE_I18N = True  # Activa la internacionalización

USE_L10N = True  # Activa la localización

USE_TZ = True  # Usa zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'  # URL base para archivos estáticos


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Tipo de campo auto-incremental por defecto para claves
