# Generated by Django 5.2.6 on 2025-10-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('Insumo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Insumo_nombre', models.CharField(max_length=30)),
                ('Insumo_precio_unitario', models.FloatField()),
                ('Insumo_cantidad', models.IntegerField()),
                ('Insumo_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_precio_total', models.FloatField(editable=False)),
                ('Insumo_cantidad_minima', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('Prenda_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Prenda_nombre', models.CharField(max_length=100)),
                ('Prenda_precio_unitario', models.FloatField()),
                ('Prenda_imagen', models.ImageField(blank=True, null=True, upload_to='prendas/')),
                ('Prenda_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='clasificaciones.color')),
                ('Prenda_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='clasificaciones.marca')),
                ('Prenda_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='clasificaciones.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='InsumosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insumo_prenda_cantidad_utilizada', models.IntegerField()),
                ('Insumo_prenda_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_prenda_costo_total', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_prendas', to='inventario.prenda')),
            ],
            options={
                'unique_together': {('insumo', 'prenda')},
            },
        ),
    ]
