# Generated by Django 5.2.6 on 2025-09-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('Insumo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Insumo_nombre', models.CharField(max_length=30)),
                ('Insumo_precio_unitario', models.FloatField()),
                ('Insumo_cantidad', models.IntegerField()),
                ('Insumo_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_precio_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('Prenda_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Prenda_nombre', models.CharField(max_length=100)),
                ('Prenda_stock', models.IntegerField()),
                ('Prenda_precio_unitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InsumosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insumo_prenda_cantidad_utilizada', models.IntegerField()),
                ('Insumo_prenda_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_prenda_costo_total', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
            ],
            options={
                'unique_together': {('insumo', 'prenda')},
            },
        ),
    ]
