# Generated by Django 5.2.6 on 2025-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumosxprendas',
            name='Insumo_prenda_unidad_medida',
            field=models.CharField(max_length=50),
        ),
    ]
