# Generated by Django 5.2.7 on 2025-10-31 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='Insumo_unidad_medida',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='Insumo_cantidad',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoinsumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida'),
            preserve_default=False,
        ),
    ]
