# Generated by Django 5.2.6 on 2025-09-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='Prenda_stock',
        ),
    ]
