# Generated by Django 5.2.7 on 2025-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tipoinsumo_unidadmedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='Insumo_unidad_medida',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
