# Generated by Django 5.2.1 on 2025-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_prenda_prenda_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='Prenda_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='Insumo_precio_total',
            field=models.FloatField(editable=False),
        ),
    ]
