# Generated by Django 5.2.1 on 2025-10-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_prenda_prenda_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='Prenda_descripcion',
        ),
        migrations.AddField(
            model_name='prenda',
            name='Prenda_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='Prenda_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='prendas/'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='Prenda_marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='Prenda_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
