# Generated by Django 5.2.7 on 2025-10-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_insumo_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='Insumo_unidad_medida',
        ),
    ]
