# Generated by Django 5.2.1 on 2025-10-13 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_prenda_prenda_descripcion_prenda_prenda_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pedido_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pedido_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Pedido_subtotal', models.FloatField(default=0)),
                ('Pedido_ganancia', models.FloatField(default=0)),
                ('Pedido_total', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='insumosxprendas',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_prendas', to='inventario.prenda'),
        ),
    ]
