# Generated by Django 5.2.7 on 2025-11-01 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0002_initial'),
        ('inventario', '0004_remove_insumo_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenda',
            options={'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AddField(
            model_name='prenda',
            name='Prenda_costo_total_produccion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='Insumo_cantidad_minima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='Insumo_precio_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipoinsumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='Prenda_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clasificaciones.color'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='Prenda_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clasificaciones.marca'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='Prenda_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clasificaciones.modelo'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='Prenda_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='Prenda_precio_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='prenda',
            table='Prenda',
        ),
    ]
