# Generated by Django 5.2.6 on 2025-09-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('Taller_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Taller_nombre', models.CharField(max_length=30)),
                ('Taller_direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='PrendasXTalleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenda_taller_mano_obra', models.FloatField()),
                ('Prenda_taller_total', models.FloatField()),
                ('insumo_x_prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prendas_talleres', to='inventario.insumosxprendas')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.taller')),
            ],
            options={
                'unique_together': {('prenda', 'taller')},
            },
        ),
    ]
