# Generated by Django 5.2.6 on 2025-10-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prendasxtalleres',
            name='insumo_x_prenda',
        ),
    ]
