# Generated by Django 5.2.6 on 2025-10-15 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificaciones', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pedido_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pedido_fecha', models.DateField()),
                ('Pedido_estado', models.BooleanField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISA', 'Lisa'), ('ESTAMPADA', 'Estampada')], default='LISA', max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_materiales', models.FloatField(default=0, editable=False)),
                ('costo_mano_obra_costura', models.FloatField(default=0, editable=False)),
                ('costo_estampado', models.FloatField(default=0, editable=False)),
                ('precio_unitario', models.FloatField(default=0, editable=False)),
                ('precio_total', models.FloatField(default=0, editable=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.modelo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.talle')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido_prenda_cantidad', models.IntegerField()),
                ('Pedido_prenda_precio_total', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
            ],
            options={
                'unique_together': {('pedido', 'prenda')},
            },
        ),
    ]
