# Generated by Django 5.2.6 on 2025-11-05 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificaciones', '0002_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pedido_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pedido_fecha', models.DateField(auto_now_add=True)),
                ('Pedido_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Pedido_estado', models.CharField(choices=[('PENDIENTE_DUENO', 'Pendiente Dueño'), ('APROBADO_DUENO', 'Aprobado - En Costura'), ('PENDIENTE_COSTURERO', 'Pendiente Costurero'), ('EN_PROCESO_COSTURERO', 'En Proceso Costurero'), ('PENDIENTE_ESTAMPADO', 'Pendiente Estampado'), ('EN_PROCESO_ESTAMPADO', 'En Proceso Estampado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_DUENO', max_length=30)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('costurero_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_costurero', to=settings.AUTH_USER_MODEL)),
                ('estampador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_estampador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISA', 'Lisa'), ('ESTAMPADA', 'Estampada')], default='LISA', max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_materiales', models.FloatField(default=0, editable=False)),
                ('costo_mano_obra_costura', models.FloatField(default=0, editable=False)),
                ('costo_estampado', models.FloatField(default=0, editable=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.modelo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
                ('talle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.talle')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido_prenda_cantidad', models.IntegerField()),
                ('Pedido_prenda_precio_total', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
            ],
            options={
                'unique_together': {('pedido', 'prenda')},
            },
        ),
    ]
