# Generated by Django 5.2.6 on 2025-09-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pedido_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pedido_fecha', models.DateField()),
                ('Pedido_estado', models.BooleanField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido_prenda_cantidad', models.IntegerField()),
                ('Pedido_prenda_precio_total', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
            ],
            options={
                'unique_together': {('pedido', 'prenda')},
            },
        ),
    ]
