# Generated by Django 5.2.6 on 2025-10-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0001_initial'),
        ('inventario', '0002_remove_prenda_prenda_stock'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LISA', 'Lisa'), ('ESTAMPADA', 'Estampada')], default='LISA', max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_materiales', models.FloatField(default=0, editable=False)),
                ('costo_mano_obra_costura', models.FloatField(default=0, editable=False)),
                ('costo_estampado', models.FloatField(default=0, editable=False)),
                ('precio_unitario', models.FloatField(default=0, editable=False)),
                ('precio_total', models.FloatField(default=0, editable=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.modelo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prenda')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.talle')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
    ]
