# Generated by Django 5.2.7 on 2025-11-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Pedido_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
