# Generated by Django 5.2.6 on 2025-10-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_usuario'),
        ('pedidos', '0002_detallepedido'),
    ]

    operations = [
    ]
