# Generated by Django 5.2.6 on 2025-11-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_add_costurero_workflow'),
        ('pedidos', '0003_update_only_estados'),
    ]

    operations = [
    ]
