# Generated by Django 5.2.7 on 2025-11-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0002_initial'),
        ('pedidos', '0003_pedido_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.color'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.marca'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.modelo'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clasificaciones.talle'),
        ),
    ]
