# Generated by Django 5.2.7 on 2025-11-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0002_initial'),
        ('pedidos', '0004_alter_detallepedido_color_alter_detallepedido_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.color'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.marca'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.modelo'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.talle'),
        ),
    ]
