# Generated by Django 5.2.6 on 2025-11-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_merge_20251105_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidosXPrendas',
        ),
    ]
