# Generated by Django 5.2.7 on 2025-11-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_detallepedido_color_alter_detallepedido_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Pedido_estado',
            field=models.CharField(choices=[('PENDIENTE_DUENO', 'Pendiente Dueño'), ('APROBADO_DUENO', 'Aprobado - En Costura'), ('PENDIENTE_ESTAMPADO', 'Pendiente Estampado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_DUENO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Pedido_fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
