# Generated by Django 5.2.6 on 2025-09-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('Insumo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Insumo_nombre', models.CharField(max_length=30)),
                ('Insumo_precio_unitario', models.FloatField()),
                ('Insumo_cantidad', models.IntegerField()),
                ('Insumo_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_precio_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('Prenda_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Prenda_stock', models.IntegerField()),
                ('Prenda_precio_unitario', models.FloatField()),
                ('Prenda_descripcion', models.CharField(max_length=100)),
                ('Prenda_color', models.CharField(max_length=20)),
                ('Prenda_talle', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Rol_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rol_nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('Taller_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Taller_nombre', models.CharField(max_length=30)),
                ('Taller_direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='InsumosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insumo_prenda_cantidad_utilizada', models.IntegerField()),
                ('Insumo_prenda_unidad_medida', models.CharField(max_length=10)),
                ('Insumo_prenda_costo_total', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.insumo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
            ],
            options={
                'unique_together': {('insumo', 'prenda')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario_nombre', models.CharField(max_length=20)),
                ('Usuario_apellido', models.CharField(max_length=20)),
                ('Usuario_email', models.CharField(max_length=40)),
                ('Usuario_dni', models.BigIntegerField()),
                ('Usuario_contrasena', models.CharField(max_length=30)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='mi_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Pedido_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pedido_fecha', models.DateField()),
                ('Pedido_estado', models.BooleanField()),
                ('Pedido_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido_prenda_cantidad', models.IntegerField()),
                ('Pedido_prenda_precio_total', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
            ],
            options={
                'unique_together': {('pedido', 'prenda')},
            },
        ),
        migrations.CreateModel(
            name='PrendasXTalleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenda_taller_mano_obra', models.FloatField()),
                ('Prenda_taller_total', models.FloatField()),
                ('insumo_x_prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prendas_talleres', to='mi_app.insumosxprendas')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.taller')),
            ],
            options={
                'unique_together': {('prenda', 'taller')},
            },
        ),
        migrations.CreateModel(
            name='RolesXUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
            options={
                'unique_together': {('rol', 'usuario')},
            },
        ),
    ]
