# Generated by Django 5.2.6 on 2025-09-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('Color_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Color_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Marca_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Marca_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('Modelo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('Talle_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Talle_codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='prenda',
            old_name='Prenda_descripcion',
            new_name='Prenda_nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Pedido_usuario',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='Prenda_color',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='Prenda_talle',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.CreateModel(
            name='ColoresXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.color')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
            ],
            options={
                'unique_together': {('color', 'prenda')},
            },
        ),
        migrations.CreateModel(
            name='MarcasXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.marca')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
            ],
            options={
                'unique_together': {('marca', 'prenda')},
            },
        ),
        migrations.CreateModel(
            name='ModelosXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.modelo')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
            ],
            options={
                'unique_together': {('modelo', 'prenda')},
            },
        ),
        migrations.CreateModel(
            name='TallesXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.prenda')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.talle')),
            ],
            options={
                'unique_together': {('talle', 'prenda')},
            },
        ),
    ]
