# Generated by Django 5.2.6 on 2025-09-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_color_marca_modelo_talle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario'),
        ),
    ]
