# Generated by Django 5.2.6 on 2025-09-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Rol_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Rol_nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario_nombre', models.CharField(max_length=20)),
                ('Usuario_apellido', models.CharField(max_length=20)),
                ('Usuario_email', models.CharField(max_length=40)),
                ('Usuario_dni', models.BigIntegerField()),
                ('Usuario_contrasena', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RolesXUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('rol', 'usuario')},
            },
        ),
    ]
