# Generated by Django 5.2.6 on 2025-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dni',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
