# Generated by Django 5.2.1 on 2025-10-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilusuario_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesxusuarios',
            name='rol',
        ),
        migrations.AlterUniqueTogether(
            name='rolesxusuarios',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolesxusuarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='RolesXUsuarios',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
