# Generated by Django 5.2.6 on 2025-10-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('Color_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Color_nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['Color_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Marca_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Marca_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['Marca_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('Modelo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['Modelo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('Talle_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Talle_codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Talle',
                'verbose_name_plural': 'Talles',
                'ordering': ['Talle_codigo'],
            },
        ),
        migrations.CreateModel(
            name='TallesXPrendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Talle disponible',
                'verbose_name_plural': 'Talles disponibles',
            },
        ),
    ]
