# Generated by Django 5.2.6 on 2025-10-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0001_initial'),
        ('inventario', '0006_alertastock_delete_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallesxprendas',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tallesxprendas',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tallesxprendas',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles_disponibles', to='inventario.prenda'),
        ),
    ]
