# Generated by Django 5.2.6 on 2025-10-15 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificaciones', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallesxprendas',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles_disponibles', to='inventario.prenda'),
        ),
        migrations.AddField(
            model_name='tallesxprendas',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificaciones.talle'),
        ),
        migrations.AlterUniqueTogether(
            name='tallesxprendas',
            unique_together={('talle', 'prenda')},
        ),
    ]
