# Generated by Django 5.2.6 on 2025-10-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0002_tallesxprendas_stock_tallesxprendas_stock_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallesxprendas',
            name='stock_minimo',
        ),
    ]
