# Generated by Django 5.2.6 on 2025-10-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificaciones', '0003_remove_tallesxprendas_stock_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallesxprendas',
            name='stock',
        ),
    ]
